services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: eventease-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["bash", "/usr/local/bin/entrypoint.sh"]

  db:
    image: postgres:15
    container_name: eventease-db
    restart: always
    environment:
      POSTGRES_DB: eventease
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  phpmyadmin:
    image: dpage/pgadmin4
    container_name: eventease-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  db_data:
